### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lauaall** [cyclone-github/base64_2_pbkdf2sha1#2]

**Comment by cyclone-github** [comment]
Feel free to messaged me on Discord and I can walk you through using the program. You can find me on hashkiller and hashmob Discord channels as well. 

1. Keep in mind, Go is the language this program is written in, so you don't actually need to know anything about Go in order to use the program. :) Having said that, you don't need Go or VSCode installed. Just download the `base64_2_pbkdf2sha1.xxx` binary for your OS and run it as shown under `Example Usage`. 
2. This is a CLI (Command Line Interface) based program, so you'll need to open a command prompt on windows, or terminal on Linux to run the program. The converted hashes are printed to stdout. If the program does not print anything to stdout, that typically means it did not find any valid PBKDF2-HMAC-SHA1 base64 hashes in the input file.
